##João Augusto Silva Bottrel - RID0468 (Dinamica DNC DEX Day_07)

Objetivo: Criar um modelo de recomendação baseado em um histórico de vendas, produtos e reviews de uma plataforma de e-commerce

#0. Importando Bibliotecas

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

#1. Importando o Dataset

In [2]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

Mounted at /content/gdrive


In [3]:
path1='/content/gdrive/MyDrive/Colab Notebooks/Bases/DNC_order_items_dataset.csv'
df_items=pd.read_csv(path1,index_col='Unnamed: 0')

In [4]:
path2='/content/gdrive/MyDrive/Colab Notebooks/Bases/DNC_order_reviews_dataset.csv'
df_reviews=pd.read_csv(path2,index_col='Unnamed: 0')

In [5]:
path3='/content/gdrive/MyDrive/Colab Notebooks/Bases/DNC_orders_dataset.csv'
df_orders=pd.read_csv(path3,index_col='Unnamed: 0')

In [6]:
path4='/content/gdrive/MyDrive/Colab Notebooks/Bases/DNC_products_dataset.csv'
df_products=pd.read_csv(path4,index_col='Unnamed: 0')

#2. Análise inicial dos dados

##2.1 Dataset de itens

In [7]:
df_items.sample(5)

order_id  ...  price
29931  4409a8e68e232a6718d156e93a58f3ec  ...   30.6
55741  7ec1a2c6522b9fcb54c68a4f8ff6f331  ...   77.5
67114  996763a377a7e96ea28f02058d1e1883  ...  199.0
57542  82eba8671de9a5c76c7f3edfcd993955  ...   34.9
8923   1469262ec8414d0e3f821bda79cf14cc  ...   38.9

[5 rows x 4 columns]

O dataset de itens possui como variáveis:        
* order_id = identificador do pedido de compra,
* order_tem_id = número de produtos em uma mesma compra,
* product_id = identificador do produto

In [8]:
df_items['order_id'].value_counts()

8272b63d03f5f79c56e9e4120aec44ef    21
ab14fdcfbe524636d65ee38360e22ce8    20
1b15974a0141d54e36626dca3fdc731a    20
9ef13efd6949e4573a18964dd1bbe7f5    15
428a2f660dc84138d969ccd69a0ab6d5    15
                                    ..
f9207b5726780645ebba8401ccc336c6     1
ff07ff058c25c993a564127557043c5a     1
bc2e4d7ad808e01f4e639fc4c447966a     1
d15a4add9a1af2006ad10d70d9a4b634     1
9827d07ad9392a9fff10d7b9f6c05f7e     1
Name: order_id, Length: 98666, dtype: int64

O resultado acima indica que tem alguns pedidos de compra que possui diversos produtos

In [9]:
df_items.shape #Verificar o tamanho do dataset

(112650, 4)

##2.2 Dataset de reviews

In [10]:
df_reviews.sample(5)

review_id  ... review_score
71041  3fbb9f98fa47e6456c2e228882107944  ...            4
86656  e8b089ecc2f8aa46c9893626bae20cf8  ...            5
42037  676890677144bf02e6674985b3b620cd  ...            3
45176  9e25d6e3025e9b9a0fc7f03588d33e2b  ...            1
82937  2bc3e0fbe51f83f0a4ff9ae1852b01f9  ...            4

[5 rows x 3 columns]

O dataset de reviews possui como variáveis:        
* order_id = identificador do pedido de compra,
* review_id = identificador da revisão do pedido de compra,
* review_score = nota ( 1 a 5) que o consumidor atribuiu ao pedido de compra

In [11]:
df_reviews.shape #Verificar o tamanho do dataset

(99224, 3)

##2.3 Dataset de ordens



In [12]:
df_orders.sample(5)

order_id  ... order_status
37141  e0ef63a06438a4f6dfa047fc41217f8e  ...    delivered
13458  052b35671e2bdd45aa889c5fa09e2809  ...    delivered
8179   72fb560d115ecf3b15de9b853c02e505  ...    delivered
82798  6e1fdac1871d58f1e81976be36a2634a  ...    delivered
77248  390056468c27192af8354d708051054e  ...    delivered

[5 rows x 3 columns]

O dataset de orders possui como variáveis:        
* order_id = identificador do pedido de compra,
* customer_id = identificador do usuário que efetuou a compra,
* order_status = status da entrega do produto

In [13]:
df_orders.shape #Verificar o tamanho do dataset

(99441, 3)

##2.4 Dataset de produtos

In [14]:
df_products.sample(5)

product_id  ... product_width_cm
19284  35ffbac108d291eae9a8df90f92f6fad  ...             25.0
27156  c7a94c6dde9d81dc864941084dbdfe45  ...             15.0
10049  92b82f3b6d4670bba0ae207094f1d226  ...             40.0
17993  f6a84928571f68635beb0f5c9333c6f3  ...             36.0
5323   ec6bda3514b2616da08c5139893b14d2  ...             16.0

[5 rows x 8 columns]

O dataset de orders possui como variáveis:        
* product_id = identificador do produto,
* product_category_name = Categoria do produto,
* product_name_length = Tamanho do nome do produto
* product_description_length = comprimento do produto
* products_weight_g = peso do produto em g
* products_lenght_cm = comprimento do produto em cm
* products_height_cm = Altura do produto em cm
* product_widht_cm = largura do produto em cm

In [15]:
df_products.shape #Verificar o tamanho do dataset

(32951, 8)

In [16]:
df_products['product_category_name'].value_counts() #Avaliando quantidade de produtos por categoria

cama_mesa_banho                  3029
esporte_lazer                    2867
moveis_decoracao                 2657
beleza_saude                     2444
utilidades_domesticas            2335
                                 ... 
casa_conforto_2                     5
fashion_roupa_infanto_juvenil       5
pc_gamer                            3
seguros_e_servicos                  2
cds_dvds_musicais                   1
Name: product_category_name, Length: 73, dtype: int64

#3 Tratamento e limpeza dos dados

Aqui vamos unir os datasets de items e reviews utilizando o order_id como chave em seguida repetir o procedimento para o dataset de orders

In [17]:
df4 = pd.merge(df_items,df_reviews,how='inner',on='order_id')

In [18]:
df4.isnull().sum()

order_id         0
order_item_id    0
product_id       0
price            0
review_id        0
review_score     0
dtype: int64

In [19]:
df3 = pd.merge(df4,df_orders,how='inner',on='order_id')

In [20]:
df3.head()

order_id  ...  order_status
0  00010242fe8c5a6d1ba2dd792cb16214  ...     delivered
1  00018f77f2f0320c557190d7a144bdd3  ...     delivered
2  000229ec398224ef6ca0657da4fc703e  ...     delivered
3  00024acbcdf0a6daa1e931b038114c75  ...     delivered
4  00042b26cf59d7ce69dfabb4e55b4fd9  ...     delivered

[5 rows x 8 columns]

A seguir iremos unir com o dataset de produtos utilizando o ID do produto como chave

In [21]:
df2 = pd.merge(df3,df_products,how='inner',on='product_id')

In [22]:
df2.sample(5)

order_id  ...  product_width_cm
11706   c33af7b181d4da454737cbdb08450735  ...              18.0
60606   acc957c82b00d1fb5b75a1f27a6d5a5c  ...              23.0
88049   58527ee4726911bee84a0f42cdd797c1  ...              38.0
106283  c2411b9c7822d227e3e48018405a0594  ...              29.0
69998   284d9d5dfbec3d66bf57c38628892577  ...              11.0

[5 rows x 15 columns]

Vamos utilizar como métrica as reviews dos usuários para criar um método de recomendação utilizando um filtro colaborativo com um fallback dos produtos mais bem avaliados. Por isso, iremos remover as colunas que tem as caractéristicas como tamanho do produto ou quantidade de letras utilizadas na descrição, pois não agregam para a recomendação

In [23]:
df1 = df2.drop(columns=['order_id','order_item_id','price','review_id','order_status','product_name_lenght','product_description_lenght','product_weight_g','product_length_cm','product_height_cm','product_width_cm']).reindex(columns=['customer_id','product_id','product_category_name','review_score'])

In [24]:
df1.sample(10)

customer_id  ... review_score
27427   1732351234779d12dcc355581d02d7b9  ...            5
102233  fbbbf9c39662ec023c52d0169700b4d6  ...            3
62132   708761cac9260fe06a7ac1e921379700  ...            1
86440   19164000c4f2f70911bb28eb4b20325a  ...            5
99735   b24e76ff960c3a5cf88ce8852d6e9fe8  ...            4
2016    af88f4b4935d45b8c2173518c445c249  ...            5
69032   d98edf3a73e942ed1ece36e5228783f5  ...            4
82854   2967800a1e6a657df2f13ef37b65c9ba  ...            4
7154    7456113cce8651aa1338725882c6a353  ...            5
65682   135ed82d00d601dd15e861f2bf1deb93  ...            5

[10 rows x 4 columns]

In [25]:
df1.shape

(112372, 4)

Abaixo é realizado um tratamento de nulos de produtos sem categoria

In [26]:
df1.isnull().sum()

customer_id                 0
product_id                  0
product_category_name    1598
review_score                0
dtype: int64

In [27]:
df1 = df1.dropna()

In [28]:
df1.sample(5)

customer_id  ... review_score
20152  9bca1f1ee89cfc3207037cc520ac5978  ...            3
49395  0be39985ec47a13a76f780957f516a6c  ...            1
56670  1596f3450e07b5743263cf514cb9c829  ...            4
91418  642f858f2d65c052cfa9058e21181a88  ...            4
70159  f3dc55ecb71ebe4066a6efc57c6593b3  ...            5

[5 rows x 4 columns]

Supondo que o usuário entre na categoria "cama_mesa_banho" da plataforma de e-commerce, vamos criar uma matriz de recomendação que retorne itens somente dessa categoria, removendo as demais

In [29]:
df = df1[df1['product_category_name']=='cama_mesa_banho'].drop(columns='product_category_name')

In [30]:
df.sample(5)

customer_id  ... review_score
81747   3baded4af7acec322d1c4eb8b405a0b4  ...            5
85088   deba7800cadd368aa9a7fb477f78864e  ...            5
89418   158195ad490cea5aee2cd7e3e85fa3b4  ...            5
110070  91b3ab92e7279abc4955341318de42f2  ...            1
74213   9582b93f8a5b04336d13454b876e72ba  ...            1

[5 rows x 3 columns]

In [31]:
df.shape

(11137, 3)

In [32]:
df['product_id'].value_counts()

99a4788cb24856965c36a24e339b6058    482
f1c7f353075ce59d8a6f3cf58f419c9c    152
06edb72f1e0c64b14c5b79353f7abea3    146
ec2d43cc59763ec91694573b31f1c29a    130
84f456958365164420cfc80fbe4c7fab    107
                                   ... 
baf59a3a8f15ea34f04394f44bad573a      1
a54f6200fb09c904053b05461c2e91f8      1
334f9a7bc70ecefea3a1fc7dd1c7ec76      1
9f6b6b828b980352cbd59ff7a03a7277      1
48ef156012e010507e2e96a9ef9e79f0      1
Name: product_id, Length: 3009, dtype: int64

In [33]:
df.dtypes

customer_id     object
product_id      object
review_score     int64
dtype: object

Esse é o dataset que servirá de base para o modelo de recomendação

#4. Modelo de recomendação

##4.1 Matriz de recomendação

Implementando um grupo de funções para realizar um agrupamento de produtos por contagem, um agrupamento dos produtos pela média de reviews e a seleção dos n melhores produtos

In [34]:
def start_pipeline(dataf):
    return dataf.copy()

def get_product_counts(dataf):
  return dataf.groupby(by='product_id', as_index=False) \
    .agg({'customer_id': pd.Series.nunique}) \
    .rename(columns={'customer_id': 'customer_id_count'}) \
    .set_index('product_id') \
    .sort_values('customer_id_count', ascending = False)

def get_avg_ratings(dataf):
  return dataf.groupby(by='product_id', as_index=False) \
    .agg({'review_score': np.mean}) \
    .rename(columns={'review_score': 'review_score_avg'}) \
    .set_index('product_id') \
    .sort_values('review_score_avg', ascending = False)

def get_n_top_values(dataf, n):
  return dataf.head(n) \
    .index \
    .tolist()

top_product_ratings = df.pipe(start_pipeline).pipe(get_avg_ratings).pipe(get_n_top_values, n=1000) #o n irá determinar o tamanho da matriz de relacionamento

top_product_sellers = df.pipe(start_pipeline).pipe(get_product_counts).pipe(get_n_top_values, n=10)

In [35]:
top_product_ratings[:10], top_product_sellers

(['7e8a5e8789ede63ab600b65235e35fa6',
  '7bb73fff8e232153ed20fef83e34e84c',
  '7b7867b1566350578959e705c5a46b2f',
  '7b564d6b4c926ddf0a111006209e1088',
  '7b1f55eb9b85b0aa6b1d4c16108eac61',
  '7b07f25dab76a821beca96d40ee0553e',
  '7ad1208884270048a2176ff437f49a9b',
  '7aac56e58e89831fecb41998f93049ea',
  '7a6750f9cb558b9fc79dbfa0d121a589',
  '79e193444d3b3ba2e2f28d0e0f9bd97a'],
 ['99a4788cb24856965c36a24e339b6058',
  'f1c7f353075ce59d8a6f3cf58f419c9c',
  '06edb72f1e0c64b14c5b79353f7abea3',
  'ec2d43cc59763ec91694573b31f1c29a',
  '84f456958365164420cfc80fbe4c7fab',
  '777d2e438a1b645f3aec9bd57e92672c',
  '363218ba55c610b750224f90bdd34be1',
  '64fb265487de2238627ce43fe8a67efc',
  '2a2d22ae30e026f1893083c8405ca522',
  'bd6e6fce9ada76ea2db0f1912e8e478f'])

In [36]:
df.pipe(start_pipeline).pipe(get_avg_ratings)

review_score_avg
product_id                                        
7e8a5e8789ede63ab600b65235e35fa6               5.0
7bb73fff8e232153ed20fef83e34e84c               5.0
7b7867b1566350578959e705c5a46b2f               5.0
7b564d6b4c926ddf0a111006209e1088               5.0
7b1f55eb9b85b0aa6b1d4c16108eac61               5.0
...                                            ...
9f4a55260fae788c26fcbb2b934ffa52               1.0
9f683084a0b0211109fef6e538cb4767               1.0
86304b9e4529f2686bc91f37c6392801               1.0
2b3ded25b94fa59143322115fce48003               1.0
0009406fd7479715e4bef61dd91f2462               1.0

[3009 rows x 1 columns]

Criando a matriz relacionando produtos com usuários

In [37]:
matriz_de_relacionamento = df[df["product_id"].isin(top_product_ratings)].pivot_table(index='product_id', columns='customer_id', values='review_score').fillna(0)

matriz_de_relacionamento.shape

(1000, 1203)

In [38]:
matriz_de_relacionamento.sample(5)

customer_id                       00674fe0f6a6f190bd022dbca99795dc  ...  ffd294eea523f67ee8c743d3a904ee20
product_id                                                          ...                                  
062907032db5e0c065bab136233a9544                               0.0  ...                               0.0
5ef15970297e8282ea1f0e3ddc528503                               0.0  ...                               0.0
57f68d17b05e574df89591b08dab6f6a                               0.0  ...                               0.0
739e8ddbbd7a0d61e33949614a14d8cb                               0.0  ...                               0.0
3d2c99e2be6594fc0a56af7754498c7b                               0.0  ...                               0.0

[5 rows x 1203 columns]

##4.2 Similaridade de cossenos

In [39]:
from sklearn.metrics.pairwise import cosine_similarity

cos_products = cosine_similarity(matriz_de_relacionamento)

print(cos_products)
cos_products.shape

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


(1000, 1000)

Função de recomendação

In [40]:
def recomendar(id_produto):
  print(f"Produto de interesse: {id_produto}")
  try:
    idx = matriz_de_relacionamento.index.tolist().index(id_produto)
    closest_10_products = np.argsort(-cos_products[idx])[1:11]
    print(f"Retornando 10 produtos mais próximos de: {id_produto}.")
    return matriz_de_relacionamento.index[closest_10_products].tolist()
  except ValueError as e:
    print(f"O item {id_produto} não está incluso na matriz de recomendação. Retornando os 10 mais avaliados") #retorno caso o ID não esteja na matriz de relacionamento
    return top_product_sellers

##4.3 Teste do modelo

Utilizando um ID existente

In [41]:
id = 'e76572c2ae4cede1e3b2ead512423efe'

In [42]:
ids_10_mais_proximos = recomendar(id)

ids_10_mais_proximos

Produto de interesse: e76572c2ae4cede1e3b2ead512423efe
Retornando 10 produtos mais próximos de: e76572c2ae4cede1e3b2ead512423efe.


['ac1fcaf7402bfbf019afdcce1a784ad4',
 'b09cd20111b8c27705b617c3b5af7608',
 '9eacfe990da87a66d7fc95e4f97bad14',
 'e76572c2ae4cede1e3b2ead512423efe',
 'd5bf1e6386a450dd26acf14a6f41768f',
 '001b237c0e9bb435f2e54071129237e9',
 'a755921e6627c919c9693f6b34884767',
 'a73521e768a217ac6a47c1752ceaf71e',
 'a71d0bc0c279b81bda788ecaca585ca5',
 'a6d040e128bd9c3f2f4c04f27f3ffbf6']

Utilizando um ID diferente, ele retorna os top 10 de reviews daquela categoria

In [43]:
id2 = 'id_novo'

In [44]:
ids_10_mais_proximos = recomendar(id2)

ids_10_mais_proximos

Produto de interesse: id_novo
O item id_novo não está incluso na matriz de recomendação. Retornando os 10 mais avaliados


['99a4788cb24856965c36a24e339b6058',
 'f1c7f353075ce59d8a6f3cf58f419c9c',
 '06edb72f1e0c64b14c5b79353f7abea3',
 'ec2d43cc59763ec91694573b31f1c29a',
 '84f456958365164420cfc80fbe4c7fab',
 '777d2e438a1b645f3aec9bd57e92672c',
 '363218ba55c610b750224f90bdd34be1',
 '64fb265487de2238627ce43fe8a67efc',
 '2a2d22ae30e026f1893083c8405ca522',
 'bd6e6fce9ada76ea2db0f1912e8e478f']

O modelo funciona bem e sua aplicação pode ser usada na seguinte situação:
* Quando um usuário entra numa seção da loja e pesquisa um item, aparecendo assim itens da mesma categoria como sugestão para facilitar a pesquisa do usuário.

Porém tem alguns pontos de melhoria que podem ser aplicados
* Os reviews são baseadas no pedido de compra, ou seja, se o usuário fez uma compra de 5 itens, a nota vai para os 5 itens, indiferente se um produto foi mais ou menos satisfatório que o outro
* A média de reviews pode ser uma métrica que engana pois uma venda de um produto com 1 review de 5 pontos tem média maior que 200 vendas de um produto com média de 4.9, porém o último item seria mais popular.
* Algumas categorias da loja possui poucos itens como "cds_dvds_musicais" que possui 1 item, seria interessante para a empresa ter uma distribuição categorica um pouco mais abrangente para evitar possíveis erros na recomendação